### ISSUE TITLE
Italic forms now released

### ISSUE THREAD

**Issue by alex-ball** [silkeh/latex-sourcecodepro#1]
Italic forms of the Source Code Pro fonts were [released on 15 July 2015](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.010R-ro%2F1.030R-it). Could you please add support for them in this package?

**Comment by silkeh** [comment]
I've updated the fonts (and the documentation to reflect that). After some testing I will submit the new version to CTAN.
Thanks for the request!
