### ISSUE TITLE
Disable F-ligas on monotype-spaced scripts

### ISSUE THREAD

**Issue by munepi** [silkeh/latex-sourcecodepro#3]
Hi, Silke-san, @silkeh 

I am using gratefully your great work here on my daily happy TeXing!

As you can see the following LaTeX document, 
the virtual font of monotype-spaced family has enabled F-ligatures. 
Do you have the plan that you provide it with no F-ligatures?
Indeed, we may generate it by giving some command line options related to ligatures for otftotfm program.

```
%#!pdflatex
\documentclass{article}\listfiles
\usepackage{sourcecodepro}
\usepackage{alltt}
\begin{document}
We currently use \ttdefault\ as \texttt{\textbackslash ttdefault} default.
We can see that the \ttdefault\ virtual font has F-ligas below.

\noindent
\texttt{fi fl ff ffi ffl}

\begin{verbatim}
file_name fl ff ffi ffl
\end{verbatim}
\begin{alltt}
file_name fl ff ffi ffl
f{}ile_name f{}l f{}f ff{}i ff{}l
\end{alltt}
\end{document}
```

**Comment by silkeh** [comment]
Thanks for your report. I'm sorry for not responding to this issue earlier, but this *will* be fixed in the next release.

**Comment by munepi** [comment]
@silkeh 

> but this will be fixed in the next release.

I just checked 51ae1ae.

ARIGATOU GOZAIMASU.
