### ISSUE TITLE
ligatures option unclear

### ISSUE THREAD

**Issue by mbanck** [silkeh/latex-sourcecodepro#7]
the documentation does not list the valid values for the `ligatures` option, it only mentions that "e.g." `TeX` is one of them.

**Comment by silkeh** [comment]
This option is the same as the `ligatures` option from `fontspec`. I'll add that to the docs for the next release.

**Comment by mbanck** [comment]
Ok I guessed so after some digging - except that the supported values for that option aren't well documented / easily found by googling either. So if there is more than one useful option, maybe duplicate them in the documentation.
